#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Errors {
    MorphismAlreadyExists,
    MorphismNotFound,
    OnlyIdentityMorphismDiscreteCategory,
    InvalidMorphismComposition,
    InvalidMorphismCommutation,
    ObjectNotFound,
    InvalidObjectId,
    InvalidObjectMapping,
    InvalidCellMapping,
    NoObjectsInCategory,
    InvalidCategory,
    InvalidFunctorLevelMissmatch,
    InvalidFunctor,
    InvalidFunctorMappings,
    InvalidBaseFunctor,
    CannotAddMorphismToDiscreteCategory,
    NoFunctorForIdentityArrow,
    InvalidArrowNoFunctorFound,
    InvalidFactorization,
    ObjectAlreadyExists,
    IdentityMorphismNotFound,
    CategoryNotInitialized,
}
